### ISSUE TITLE
нахуй ему отдельная картинка для аватарки если этот еблан даже её нигде не показывает то

### ISSUE THREAD

**Issue by fbernkastel228** [Spbog/dotfiles#31]

**Comment by Spbog** [comment]
в каком плане? в домашней директории имеется avatar.png?

**Comment by Spbog** [comment]
и ты hyprlock хотя бы пробовал запустить?)

**Comment by fbernkastel228** [comment]
> и ты hyprlock хотя бы пробовал запустить?)

блять
